development:
  adapter: postgresql
  encoding: unicode
  database: blubank_dev
  pool: 5
  username: irvine
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: blubank_test
  pool: 5
  username: irvine
  password: 123